Create a function that will handle argument count checking.

diff --git a/playlister b/playlister
--- a/playlister
+++ b/playlister
@@ -27,10 +27,8 @@ declare -a configs_mutable=(
 )
 
 function main () {
-	if [[ "$#" -eq 0 ]]; then
-		output-failure "invalid argument count (must be > 0)"
-		exit 1
-	fi
+	# PLACEHOLDER FOR A USER-FRIENDLY ERROR
+	assert-correct-argument-count "main" ">" 0 "$@"
 	while [[ "$#" -gt 0 ]]; do
 		case $1 in 
 			config)
@@ -53,9 +51,60 @@ function main () {
 	done
 }
 
+function assert-correct-argument-count () {
+	# Check if function given correct arg amount.
+	# return execution flow on success, exit 1 on failure
+		# success: correct arg count given to function
+		# failure:
+			# wrong arg count given to assert-corr...
+			# invalid operator given
+			# assertion failed
+	# Arguments:
+		# func 				-> name of function (needed for failure output)
+		# operator 			-> keyword together with argcount specifying the argument count
+		# argcount 			-> a point of refrence for arguments expected
+		# optional arguments... 	-> arguments given originally to func
+	# the func arguments need to be inputted with [@] (protect from "My Argument" arguments with [*])
+	if ! [[ $# -ge 3 ]]; then
+		output-failure "assert-correct-argument-count: invalid argument count(must be >= 3, but {$#} were given)"
+		exit 1
+	fi
+	local func="$1"
+
+
+	local operator="$2"
+	local accepted_operators=( "==" ">" )
+	local accepted_operator
+	local inside=0
+	for accepted_operator in "${accepted_operators[@]}"; do
+		if [[ "$accepted_operator" == "$operator" ]]; then
+			inside=1
+		fi
+	done
+	if ! [[ $inside -eq 1 ]]; then
+		output-failure "assert-correct-argument-count: \"$operator\" not a valid operator( one of: ${accepted_operators[*]})"
+		exit 1
+	fi
+	local argcount="$3"
+	local positive_num_re="^[0-9]+$"
+	if ! [[ $argcount =~ $positive_num_re ]]; then
+		output-failure "assert-correct-argument-count: \"$argcount\" not a valid positive integer"
+		exit 1
+	fi
+
+	shift 3
+
+	if  ( [[ "$operator" == ">"  ]] &&  ! [[ $# -gt $argcount ]] ) || \
+	    ( [[ "$operator" == "==" ]] &&  ! [[ $# -eq $argcount ]] ) ; then
+		output-failure "${func}: invalid argument count($# !${operator} $argcount)"
+		exit 1
+	fi
+}
+
 function output-success () {
 	# unifying user success output
 	# 1 argument: the string to output
+	assert-correct-argument-count "output-success" "==" 1 "$@"
 	local output="$1"
 	local white="\e[1;37m"
 	local green="\e[1;32m"
@@ -65,6 +114,7 @@ function output-success () {
 function output-failure () {
 	# unifying user failure output
 	# 1 argument: the string to output
+	assert-correct-argument-count "output-failure" "==" 1 "$@"
 	local output="$1"
 	local white="\e[1;37m"
 	local red="\e[1;31m"
@@ -74,6 +124,7 @@ function output-failure () {
 function output-info () {
 	# unfying user informative output
 	# 1 argument: the string to output
+	assert-correct-argument-count "output-info" "==" 1 "$@"
 	local output="$1"
 	local white="\e[1;37m"
 	local yellow="\e[1;33m"
@@ -83,6 +134,7 @@ function output-info () {
 function output-question () {
 	# unifying user prompt output (used in is-confirmed)
 	# 1 argument: the string to output
+	assert-correct-argument-count "output-question" "==" 1 "$@"
 	local output="$1"
 	local white="\e[1;37m"
 	local blue="\e[1;34m"
@@ -95,10 +147,7 @@ function is-file-readable () {
 		# failure -> file is not readable
 	# return to execution flow on success, exit on failure
 	# 1 argument: the file
-	if ! [[ $# -eq 1 ]]; then
-		output-failure "invalid is-file-readable argument count(must be ==1)"
-		exit 1
-	fi
+	assert-correct-argument-count "is-file-readable" "==" 1 "$@"
 	local file="$1"
 	file="${file%/}"	# trim slash if file given for when the file given is a directory.
 	if ! [[ -r "$file" ]]; then
@@ -113,10 +162,7 @@ function is-directory-not-empty () {
 		# success -> directory is not empty 
 		# failure -> directory is empty
 	# 1 argument: the directory
-	if ! [[ $# -eq 1 ]]; then
-		output-failure "invalid is-directory-empty argument count (must be ==1)"
-		exit 1
-	fi
+	assert-correct-argument-count "is-directory-not-empty" "==" 1 "$@"
 	local directory="$1"
 
 	if ! find "$directory" -mindepth 1 -maxdepth 1 | read; then
@@ -129,12 +175,9 @@ function is-directory-not-empty () {
 
 function show () {
 	# extension of the program's main function for show options.
-	if [[ $# -eq 0 ]]; then
-		output-failure "invalid show argument count( must be >0)"
-		exit 1
-	fi
+	# PLACEHOLDER FOR A USER-FRIENDLY ERROR
+	assert-correct-argument-count "show" ">" 0 "$@"
 	declare -A items=()
-
 	
 	while ! [[ $# -eq 0 ]]; do
 		case $1 in
@@ -183,11 +226,7 @@ function output-items () {
 		# failure -> function arguments were given
 	# no arguments
 	# this function should be found after show functions in the show man function.
-	if ! [[ $# -eq 0 ]]; then
-		output-failure "output-items takes in no arguments"
-		exit 1
-	fi
-
+	assert-correct-argument-count "output-items" "==" 0 "$@"
 	local item 
 	for item in "${!items[@]}"; do
 		if [[ ${items["$item"]} -eq 1 ]] ; then
@@ -210,12 +249,9 @@ function show-playlist () {
 			# mp3_directory empty
 			# entry in playlist not valid, not to be deleted
 	# 1 argument: playlist filename(basename'd)
-	if ! [[ $# -eq 1 ]]; then
-		output-failure "invalid show-playlist argument count(must be ==1)"
-		exit 1
-	fi
+	# PLACEHOLDER FOR A USER-FRIENDLY ERROR
+	assert-correct-argument-count "show-playlist" "==" 1 "$@"
 	local playlist="$1"
-
 	is-file-readable "$playlist_directory"
 	is-directory-not-empty "$playlist_directory"
 
@@ -244,10 +280,7 @@ function is-string-valid-mp3 () {
 			# mp3 directory not readable
 			# mp3 directory empty
 	# 1 argument: string
-	if ! [[ $# -eq 1 ]]; then
-		output-failure "invalid is-string-valid-mp3 argument count(must be == 1)"
-		exit 1
-	fi
+	assert-correct-argument-count "is-string-valid-mp3" "==" 1 "$@"
 	local string="$1"
 	is-file-readable "$mp3_directory"
 	is-directory-not-empty "$mp3_directory"
@@ -267,10 +300,7 @@ function is-confirmed () {
 	# return 0 if confirmed, return 1 if rejected, exit 1 on error
 		# failures: wrong arg count
 	# 1 argument: string prompt to display
-	if ! [[ $# -eq 1 ]]; then
-		output-failure "invalid is-confirmed argument count(must be == 1)"
-		exit 1
-	fi
+	assert-correct-argument-count "is-confirmed" "==" 1 "$@"
 	local prompt="$1"
 
 	local confirmation=( "y" "ye" "yes" "Y" "Ye" "Yes" "YE" "YES" )
@@ -306,10 +336,8 @@ function show-author () {
 			# failed to add/increment author in items
 	# implementation of playlist show author <author>
 	# 1 argument: the name of the author
-	if ! [[ $# -eq 1 ]]; then
-		output-failure "invalid show-author argument count(must be ==1)"
-		exit 1
-	fi
+	# PLACEHOLDER FOR A USER-FRIENDLY ERROR
+	assert-correct-argument-count "show-author" "==" 1 "$@"
 	
 	local target_author="$1"
 	
@@ -342,10 +370,9 @@ function show-authors () {
 			# failed to add/increment author in items
 	# implementation of playlist show authors
 	# no arguments
-	if [[ $# -ne 0 ]]; then
-		output-failure "show-authors does not take any arguments"
-		exit 1
-	fi
+
+	# PLACEHOLDER FOR A USER-FRIENDLY ERROR
+	assert-correct-argument-count "show-authors" "==" 0 "$@"
 	is-file-readable "$mp3_directory"
 
 	is-directory-not-empty "$mp3_directory"
@@ -375,10 +402,9 @@ function show-mp3s () {
 			# is-mp3-used fail
 	# 1 argument: type of mp3: ["all", "used", "unused"]
 	# implementation of playlister show mp3 <type>
-	if [[ $# -ne 1 ]]; then
-		output-failure "invalid show-mp3 argument count (must be ==1)"
-		exit 1
-	fi
+
+	# PLACEHOLDER FOR A USER-FRIENDLY ERROR
+	assert-correct-argument-count "show-mp3s" "==" 1 "$@"
 	local argument="$1"
 	
 	if ! (  [[ "$argument" == "all" ]] 	|| \
@@ -423,10 +449,7 @@ function is-mp3-used () {
 			# playlist file not readable
 	# 1 argument: filename to be checked (previously basename'd!)
 	# used in show-mp3 with mp3 type distinctions
-	if [[ $# -ne 1 ]]; then
-		output-failure "invalid is-mp3-used argument count(must be ==1)"
-		exit 1
-	fi
+	assert-correct-argument-count "is-mp3-used" "==" 1 "$@"
 	local filename="$1"
 	
 	is-file-readable "$playlist_directory"
@@ -457,10 +480,9 @@ function show-playlists () {
 			# add-item exits
 	# no arguments
 	# implementation of playlister show playlists
-	if [[ $# -ne 0 ]]; then
-		output-failure "show-playlists does not take any arguments"
-		exit 1
-	fi
+
+	# PLACEHOLDER FOR A USER-FRIENDLY ERROR
+	assert-correct-argument-count "show-playlists" "==" 0 "$@"
 	is-file-readable "$playlist_directory"
 
 	is-directory-not-empty "$playlist_directory"
@@ -471,10 +493,7 @@ function show-playlists () {
 }
 
 function is-item-inside-items () {
-	if ! [[ $# -eq 1 ]]; then
-		output-failure "invalid is-item-inside-items argument count (must be ==1)"
-		exit 1
-	fi
+	assert-correct-argument-count "is-item-inside-items" "==" 1 "$@"
 	local argument="$1"
 	local item
 	for item in "${!items[@]}"; do
@@ -487,10 +506,7 @@ function is-item-inside-items () {
 
 function get-from-filename () {
 	
-	if ! [[ $# -eq 2 ]]; then
-		output-failure "invalid get-from-filename argument count (must be ==2)"
-		exit 1
-	fi
+	assert-correct-argument-count "get-from-filename" "==" 2 "$@"
 	
 	local filename="$1"
 	local option="$2"
@@ -513,6 +529,7 @@ function get-from-filename () {
 }
 
 function divide-authors (){
+	assert-correct-argument-count "divide-authors" "==" 1 "$@"
 	if ! [[ $# -eq 1 ]]; then
 		output-failure "invalid divide-authors argument count (must be ==1)"
 		exit 1
@@ -530,10 +547,7 @@ function add-item () {
 		# success -> item added 
 		# failure -> invalid argument count
 	# 1 argument: string item to be added 
-	if ! [[ $# -eq 1 ]]; then
-		output-failure "invalid add-item argument count(must be ==1)"
-		exit 1
-	fi
+	assert-correct-argument-count "add-item" "==" 1 "$@"
 	local new_item="$1"
 	if is-item-inside-items "$new_item"; then
 		items["$new_item"]=$(( ${items["$new_item"]} + 1 ))
@@ -543,10 +557,8 @@ function add-item () {
 }
 
 function config () {
-	if [[ "$#" -eq 0 ]]; then
-		output-failure "invalid config argument count (must be >0)"
-		exit 1
-	fi
+	# PLACEHOLDER FOR A USER-FRIENDLY ERROR
+	assert-correct-argument-count "config" ">" 0 "$@"
 	while [[ "$#" -gt 0 ]]; do
 		case $1 in
 			configure)
@@ -619,10 +631,8 @@ function config-list () {
 }
 
 function config-get () {
-	if [[ $# -ne 1 ]]; then
-		output-failure "invalid config get argument count(must be ==1)"
-		exit 1
-	fi
+	# PLACEHOLDER FOR A USER-FRIENDLY ERROR
+	assert-correct-argument-count "config-get" "==" 1 "$@"
 	local argument="$1"
 	if ! is-valid-config "$argument" ; then
 		output-failure "not a valid configuration: \"$argument\""
@@ -632,11 +642,8 @@ function config-get () {
 }
 
 function config-set () {
-	if [[ $# -ne 2 ]]; then
-		output-failure "invalid config set argument count(must be ==2)"
-		exit 1
-	fi
-	
+	# PLACEHOLDER FOR A USER-FRIENDLY ERROR
+	assert-correct-argument-count "config-set" "==" 2 "$@"
 	local config_file_name="$( basename "$config_file" )"
 	
 	if ! [[ -w "$config_file" ]]; then
@@ -669,6 +676,7 @@ function config-set () {
 }
 
 function create-directory () {
+	assert-correct-argument-count "create-directory" "==" 1 "$@"
 	local directory="$1"
 	local directoryname="$(basename "$1")"
 	if [[ -d "$directory" ]]; then
@@ -687,6 +695,7 @@ function create-directory () {
 }
 
 function setup-file () {
+	assert-correct-argument-count "setup-file" ">" 1 "$@"
 	local filepath="$1"
 	local filename="$( basename "$filepath" )"
 	local backup="no"
@@ -800,6 +809,7 @@ function read-config-if-exists () {
 }
 
 function is-valid-config (){
+	assert-correct-argument-count "is-valid-config" "==" 1 "$@"
 	local argument="$1"
 	local configuration
 	for configuration in "${!configs[@]}"; do
@@ -811,6 +821,7 @@ function is-valid-config (){
 }
 
 function change-configs-to-tmp () {
+	assert-correct-argument-count "change-configs-to-tmp" "==" 2 "$@"
 	local config="$1"
 	local value="$2"
 	local found="no"
@@ -829,6 +840,7 @@ function change-configs-to-tmp () {
 }
 
 function is-valid-config-mutable () {
+	assert-correct-argument-count "is-valid-config-mutable" "==" 1 "$@"
 	local argument="$1"
 	local configuration
 	for configuration in "${configs_mutable[@]}"; do
@@ -841,8 +853,9 @@ function is-valid-config-mutable () {
 }
 
 function get-config () {
-    local argument="$1"
-    output-info "	$argument	-> 	${configs[$argument]} "
+	assert-correct-argument-count "get-config" "==" 1 "$@"
+	local argument="$1"
+    	output-info "	$argument	-> 	${configs[$argument]} "
 }
 
 main "$@"
