Add main function

diff --git a/playlister b/playlister
--- a/playlister
+++ b/playlister
@@ -13,3 +13,26 @@ playlist_directory="${main_directory}playlists/"
 mp3_directory="/mp3s"
 mp3_ext=".mp3"
 playlist_ext=".plst"
+
+function main () {
+	if [[ "$#" -eq 0 ]]; then
+		>&2 echo "$0: invalid argument count (must be > 0)!"
+		exit 1
+	fi
+	while [[ "$#" -gt 0 ]]; do
+		case $1 in 
+			config)
+				shift
+				>&2 echo "$0: config handling not configured yet!"
+				exit 1
+				;;
+			*)
+				>&2 echo "$0: unrecognised option!"
+				shift
+				exit 1
+				;;
+		esac
+	done
+}
+
+main "$@"
