Create the setup-file function. This function is made to unify the set up of files for code reusage. I figured that instead of rewriting 90% of the code from helpfile setup for database and user config files, i can create a function and handle them separately by arguments. By implementing a while case argument loop (like in the main) inside this function I also gain the advantage to having a file be checked for both backup and current directory existence.

diff --git a/playlister b/playlister
--- a/playlister
+++ b/playlister
@@ -61,26 +61,29 @@ function config-configure () {
 	if ! create-directory "$main_directory" ; then
 		exit 1
 	fi
-	user-output "end"
-	exit 1
 	
-	if ! [[ -a "$helpfile" ]]; then
-		user-output "$helpfile not found!"
-		local helpfilename="$(basename $helpfile)"
-		if ! [[ -a "./$helpfilename" ]] ; then
-			user-output "$helpfilename not found in current directory!"
-			exit 1
-		fi
-		user-output "$helpfilename found in current directory."
-		mv $helpfilename $helpfile
-		if ! [[ $? -eq 0 ]]; then
-			user-output "$helpfilename failed to move to $helpfile !"
-			exit 1
-		fi
-		user-output "$helpfilename moved to $helpfile ."
-	else
-		user-output "$helpfile exists."
+	if ! setup-file "$helpfile"; then
+		user-output "failed to set up $helpfile !"
+		exit 1
 	fi
+	
+	# if ! [[ -a "$helpfile" ]]; then
+		# user-output "$helpfile not found!"
+		# local helpfilename="$(basename $helpfile)"
+		# if ! [[ -a "./$helpfilename" ]] ; then
+			# user-output "$helpfilename not found in current directory!"
+			# exit 1
+		# fi
+		# user-output "$helpfilename found in current directory."
+		# mv $helpfilename $helpfile
+		# if ! [[ $? -eq 0 ]]; then
+			# user-output "$helpfilename failed to move to $helpfile !"
+			# exit 1
+		# fi
+		# user-output "$helpfilename moved to $helpfile ."
+	# else
+		# user-output "$helpfile exists."
+	# fi
 	
 }
 
@@ -100,4 +103,10 @@ function create-directory () {
 	fi
 	return 0
 }
+
+function setup-file () {
+	local filepath="$1"
+	echo "$filepath is being set up."
+}
+
 main "$@"
