Implement show mp3.

diff --git a/playlister b/playlister
--- a/playlister
+++ b/playlister
@@ -153,6 +153,12 @@ function show () {
 				output-items
 				exit 1
 				;;
+			mp3)
+				shift
+				show-mp3 "$@"
+				output-items
+				exit 1
+				;;
 			*)
 				output-failure "unrecognised show option:\"$1\""
 				exit 1
@@ -176,6 +182,38 @@ function output-items () {
 		else
 			echo -e "\t$item \t[${items[$item]}]"
 		fi
+	done
+}
+
+function show-mp3 () {
+	# add every playlist to items, if playlist has $mp3name
+	# return execution on success, ext 1 on failure
+		# failure:
+			# wrong arg count
+			# argument not a  valid mp3 file
+			# playlist directory not readable or is empty
+			# a playlist file is not readable
+	# 1 argument:
+		# basenamed filename of the mp3 file
+	assert-correct-argument-count "show-mp3" "==" 1 "$@"
+
+	local mp3name="$1"
+	if ! is-string-valid-mp3 "$mp3name"; then
+		output-failure "\"$mp3name\" not a valid mp3 file"
+		exit 1
+	fi
+
+	assert-file-readable "$playlist_directory"
+	is-directory-not-empty "$playlist_directory"		
+
+	for file in "${playlist_directory}"*; do
+		local filename="$(basename "$file" )"
+		assert-file-readable "$file"
+		while read line; do 
+			if [[ "$line" == "$mp3name" ]]; then
+				add-item "$filename"
+			fi
+		done < "$file"
 	done
 }
 
@@ -205,7 +243,6 @@ function show-playlist () {
 	assert-file-readable "$mp3_directory"
 	is-directory-not-empty "$mp3_directory"
 	while IFS= read -ru 69 entry; do
-		echo "Trying entry: \"$entry\""
 		if ! is-string-valid-mp3 "$entry"; then
 			output-failure "\"$entry\" is not a valid mp3 file"
 			if ! is-confirmed "Delete \"$entry\" from \"$playlist\""; then
@@ -801,7 +838,7 @@ function get-config () {
     	output-info "	$argument	-> 	${config2value[$argument]} "
 }
 
-function is-directory-not-empty () {
+function is-directory-not-empty () {		# need to change it to assert-
 	# check if directory is empty
 	# return to execution flow on success, exit on failure
 		# success -> directory is not empty 
