Reimplement show-music to use add-item instead of update-items

diff --git a/playlister b/playlister
--- a/playlister
+++ b/playlister
@@ -54,6 +54,7 @@ function main () {
 }
 
 function output-success () {
+	# unifying user success output
 	local output="$1"
 	local white="\e[1;37m"
 	local green="\e[1;32m"
@@ -61,6 +62,7 @@ function output-success () {
 }
 
 function output-failure () {
+	# unifying user failure output
 	local output="$1"
 	local white="\e[1;37m"
 	local red="\e[1;31m"
@@ -68,6 +70,7 @@ function output-failure () {
 }
 
 function output-info () {
+	# unfying user informative output
 	local output="$1"
 	local white="\e[1;37m"
 	local yellow="\e[1;33m"
@@ -130,6 +133,7 @@ function is-directory-not-empty () {
 
 
 function show () {
+	# extension of the program's main function for show options.
 	if [[ $# -eq 0 ]]; then
 		output-failure "invalid show argument count( must be >0)"
 		exit 1
@@ -202,6 +206,7 @@ function show-author () {
 			# mp3 directory empty, 
 			# failed to add/increment author in items
 	# implementation of playlist show author <author>
+	# 1 argument: the name of the author
 	if ! [[ $# -eq 1 ]]; then
 		output-failure "invalid show-author argument count(must be ==1)"
 		exit 1
@@ -237,6 +242,7 @@ function show-authors () {
 			# mp3 directory empty, 
 			# failed to add/increment author in items
 	# implementation of playlist show authors
+	# no arguments
 	if [[ $# -ne 0 ]]; then
 		output-failure "show-authors does not take any arguments"
 		exit 1
@@ -259,13 +265,26 @@ function show-authors () {
 }
 
 function show-music () {
+	# adds every mp3 file to items
+	# return execution flow on success, exit 1 on failure
+		# success: all files were looped and added to items
+		# failures:
+			# wrong arg count
+			# arg not in ["all", "used", "unused"]
+			# mp3 directory not readable
+			# mp3 directory empty
+			# is-music-used fail
+	# 1 argument: type of music: ["all", "used", "unused"]
+	# implementation of playlister show music <type>
 	if [[ $# -ne 1 ]]; then
 		output-failure "invalid show-music argument count (must be ==1)"
 		exit 1
 	fi
 	local argument="$1"
 	
-	if ! ( [[ "$argument" == "all" ]] || [[ "$argument" == "used" ]] || [[ "$argument" == "unused" ]] ); then
+	if ! (  [[ "$argument" == "all" ]] 	|| \
+		[[ "$argument" == "used" ]] 	|| \
+		[[ "$argument" == "unused" ]] 	); then
 		output-failure "invalid show-music argument:\"$argument\""
 		exit 1
 	fi
@@ -274,32 +293,42 @@ function show-music () {
 	is-directory-not-empty "$mp3_directory"
 	local file
 	for file in "${mp3_directory}"*; do
+		filename="$(basename "$file" )"
+
 		if [[ "$argument" == "all" ]]; then
-			if ! update-items "$( basename "$file" )" "music"; then
-				exit 1
-			fi
+			add-item "$filename"
+
 		elif [[ "$argument" == "used" ]]; then
-			if is-music-used "$file"; then
-				if ! update-items "$( basename "$file" )" "music"; then
-					exit 1
-				fi
+			if is-music-used "$filename"; then
+				add-item "$filename"
 			fi
+
 		else #unused
-			if ! is-music-used "$file"; then
-				if ! update-items "$( basename "$file" )" "music"; then
-					exit 1
-				fi
+			if ! is-music-used "$filename"; then
+				add-item "$filename"
 			fi
 		fi
 	done
 }
 
 function is-music-used () {
+	# checks if mp3 file is entry in a playlist
+	# return int status as value, exit 1 on error
+		# success: return status
+			# 0 -> music is used
+			# 1 -> music is not used
+		# failure:
+			# wrong arg count
+			# playlist directory not readable
+			# playlist directory empty
+			# playlist file not readable
+	# 1 argument: filename to be checked (previously basename'd!)
+	# used in show-music with music type distinctions
 	if [[ $# -ne 1 ]]; then
 		output-failure "invalid is-music-used argument count(must be ==1)"
 		exit 1
 	fi
-	local filename="$(basename "$1")"
+	local filename="$1"
 	
 	is-directory-readable "$playlist_directory"
 
